NewFuzzing

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -54,7 +54,6 @@ jobs:
           name: sast-results-${{ github.sha }}
           path: codeql-results.sarif
 
-
   fuzzing:
     name: Fuzzing Analysis
     needs: integration
@@ -69,20 +68,22 @@ jobs:
       - name: Run OWASP ZAP Fuzzing
         run: |
           TARGET_URL="https://coride.site"
-          docker run --user root --rm -v $(pwd)/results:/zap/results:rw zaproxy/zap-stable zap-full-scan.py \
+          docker run --user root --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-full-scan.py \
             -t $TARGET_URL \
-            -r /zap/results/fuzz-report.html || true
+            -r /zap/wrk/fuzz-report.html || true
+
+      - name: List Results Directory
+        run: ls -la .
+
       - name: Verify Results
         run: |
-          test -f ./results/fuzz-report.html && echo "fuzz-report.html exists" || echo "fuzz-report.html is missing"
+          test -f ./fuzz-report.html && echo "fuzz-report.html exists" || echo "fuzz-report.html is missing"
+
       - name: Upload Fuzzing Results
         uses: actions/upload-artifact@v4
         with:
           name: fuzzing-results-${{ github.sha }}
-          path: ./results/fuzz-report.html
-
-
-
+          path: ./fuzz-report.html
 
   dast:
     name: DAST Analysis
